---
name: monospacee
services:
  web:
    container_name: monospacee-web
    image: monospacee
    build: ./frontend
    restart: unless-stopped
    ports:
      - 9001:3000
  og:
    container_name: monospacee-og
    image: monospacee_og
    build: ./og
    restart: unless-stopped
    ports:
      - 9002:5174
