---
name: monospacee
services:
  web:
    container_name: monospacee-web
    image: monospacee
    build: ./frontend
    restart: unless-stopped
    ports:
      - 9001:3000
    labels:
      - homepage.group=Websites
      - homepage.name=Monospacee
      - homepage.icon=http://192.168.88.21:9001/favicon.png
      - homepage.href=https://monospac.ee
      - homepage.siteMonitor=https://monospac.ee
